[general]
live_config_reload = true

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"
resize_increments = false
padding = { x = 20, y = 20 }

[font]
normal = { family = "monospace_font", style = "Regular" }
bold = { family = "monospace_font", style = "Bold" }
italic = { family = "monospace_font", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }
size = 10.0

[colors]
transparent_background_colors = false
cursor = { cursor = "CellForeground", text = "CellBackground" }
primary = { background = '0x0c0f0a', foreground = '0xd7d0c7' }
selection = { background = "CellForeground", text = "CellBackground" }

[colors.bright]
black = '0x404040'
red = '0xd23d3d'
green = '0xb9d7a8'
yellow = '0xf39d21'
blue = '0x4e9fb1'
magenta = '0xa87cb5'
cyan = '0x42717b'
white = '0xdddddd'

[colors.normal]
black = '0x101010'
red = '0xe84f4f'
green = '0xd7e8cd'
yellow = '0xe1aa5d'
blue = '0x7dc1cf'
magenta = '0xce98c0'
cyan = '0x6d878d'
white = '0xf2f2f2'

# [bell]
# animation = "EaseOut"
# duration = 500
# color = "0x568f57"
# command = { program = "paplay", args = [
#   "/usr/share/sounds/freedesktop/stereo/complete.oga",
# ] }

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
blink_interval = 500
style = { blinking = "On", shape = "Block" }

[mouse]
hide_when_typing = false
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Left", mods = "Alt", chars = "\u001Bb" },
  { key = "Right", mods = "Alt", chars = "\u001Bf" },
  { key = "Paste", action = "Paste" },
  { key = "Copy", action = "Copy" },
  { key = "L", mods = "Control", action = "ClearLogNotice" },
  { key = "L", mods = "Control", chars = "\f" },
  { key = "PageUp", action = "ScrollPageUp", mode = "~Alt", mods = "Shift" },
  { key = "PageDown", mode = "~Alt", mods = "Shift", action = "ScrollPageDown" },
  { key = "Home", mode = "~Alt", mods = "Shift", action = "ScrollToTop" },
  { key = "End", mode = "~Alt", mods = "Shift", action = "ScrollToBottom" },
]
