#!/bin/bash

userresources=$HOME/.config/X11/Xresources
sysresources=/etc/X11/xinit/.Xresources

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# start these
numlockx on
xsetroot -cursor_name left_ptr
setxkbmap -option grp:ctrls_toggle tr,es
setxkbmap -option caps:swapescape
systemctl --user import-environment DISPLAY
exec bspwm
