[general]
output_path = "~/.config/niri/config.kdl"

[genconfig]
sources = [
  "$XDG_CONFIG_HOME/niri/src/internal.kdl",
  "$XDG_CONFIG_HOME/niri/src/monitors.kdl",
  "$XDG_CONFIG_HOME/niri/src/input.kdl",
  "$XDG_CONFIG_HOME/niri/src/keybindings.kdl",
  "$XDG_CONFIG_HOME/niri/src/visual.kdl",
  "$XDG_CONFIG_HOME/niri/src/rules.kdl"
]
