#!/bin/sh

_px() {
  pgrep -x "$@"
}

_ka() {
  killall "$@"
}

# run once and never kill
_px sxhkd >/dev/null || sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc.apps "$HOME"/.config/sxhkd/sxhkdrc.bspwm "$HOME"/.config/sxhkd/sxhkdrc.dunst "$HOME"/.config/sxhkd/sxhkdrc.fn "$HOME"/.config/sxhkd/sxhkdrc.mouse >"$HOME"/.cache/logs/autostart/sxhkd.log 2>&1 &
_px playerctld >/dev/null || playerctld daemon >"$HOME"/.cache/logs/autostart/playerctld.log 2>&1 &
_px clipmenud >/dev/null || clipmenud >"$HOME"/.cache/logs/autostart/clipmenud.log 2>&1 &
_px xidlehook >/dev/null || "$HOME"/.config/xidlehook/launch.sh >"$HOME"/.cache/logs/autostart/xidlehook.log 2>&1 &
_px udiskie >/dev/null || udiskie >"$HOME"/.cache/logs/autostart/udiskie.log 2>&1 &

# kill all already running autostart programs
_ka picom >/dev/null
_ka dunst >/dev/null
_ka polybar >/dev/null
_ka mpris-proxy >/dev/null

# set wallpaper
"$HOME"/.config/feh/.fehbg &

# create a log directory for autostarted apps
[ -d ~/.cache/logs ] || mkdir ~/.cache/logs &
[ -d ~/.cache/logs/autostart ] || mkdir ~/.cache/logs/autostart &

# start picom and log errors
picom --config "$HOME"/.config/picom/picom.conf --log-level ERROR --log-file "$HOME"/.cache/logs/autostart/picom.log &

# start dunst and log
# make the verbosity debug to see which icons are missing if a notificaation doesn't have an icon
dunst -conf "$HOME"/.config/dunst/config.ini -verbosity warn >"$HOME"/.cache/logs/autostart/dunst.log 2>&1 &

# start polybar
polybar --log=error --config="$HOME"/.config/polybar/config.ini main >"$HOME"/.cache/logs/autostart/polybar.log 2>&1 &

# start bluetooth controls
mpris-proxy >"$HOME"/.cache/logs/autostart/mpris-proxy.log 2>&1 &

grep "accent =" "$HOME"/.config/polybar/config.ini | grep -o "#......" | sed "s/\#//g" >"$HOME"/.local/share/polybar/polybar-accent.dat &
grep "^foreground =" "$HOME"/.config/polybar/config.ini | grep -o "#......" | sed "s/\#//g" >"$HOME"/.local/share/polybar/polybar-foreground.dat &
grep "^bottom =" "$HOME"/.config/polybar/config.ini | sed 's/bottom = //g' >"$HOME"/.local/share/polybar/polybar-position.dat &

# unblock just in case
rfkill unblock all
