#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd 2>&1 | tee "$HOME"/.cache/autostart/sxhkd.log &
pgrep -x urxvtd > /dev/null || urxvtd -f 2>&1 | tee "$HOME"/.cache/autostart/urxvtd.log &

# workspace names
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# basic settings
bspc config window_gap		10
bspc config split_ratio		.52
bspc config gapless_monocle	true
bspc config top_padding 	0
bspc config bottom_padding	22
bspc config focus_follows_pointer true

bspc config border_width		1
bspc config focused_border_color	\#808080
bspc config normal_border_color		\#595959

# no beep
xset b 0

# mouse settings
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
#
# Change it according to your own touchpad
#
# xinput set-prop "MSFT0001:00 04F3:31BE Touchpad" "libinput Tapping Enabled" 1
# xinput set-prop "MSFT0001:00 04F3:31BE Touchpad" "libinput Tapping Enabled Default" 1
# xinput set-prop "MSFT0001:00 04F3:31BE Touchpad" "libinput Accel Profile Enabled" 1 0
# xinput set-prop "MSFT0001:00 04F3:31BE Touchpad" "libinput Accel Profile Enabled Default" 1 0
# xinput set-prop "MSFT0001:00 04F3:31BE Touchpad" "libinput Accel Profiles Available" 1 0

# rules
bspc rule -a '*:zbar' state=floating focus=on
bspc rule -a 'jetbrains-studio:*:win0' state=floating focus=on
bspc rule -a '*:dragon' state=floating sticky=on 

# startup
. /home/<your username>/.config/bspwm/autostart
