#!/bin/sh

_bc() {
  bspc config "$@"
}

_br() {
  bspc rule -a "$@"
}

_xs() {
  xinput set-prop "SYNA2BA6:00 06CB:CE2D Touchpad" "$@"
}

_xsw() {
  xinput set-prop "Lenovo Lenovo Wireless Mouse" "$@"
}

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# border
_bc border_width 0
_bc focused_border_color "#83c984"
_bc normal_border_color "#4eb14f"

# etc
_bc focus_follows_pointer true
_bc gapless_monocle true
_bc split_ratio .52
_bc window_gap 10

# mouse settings
_bc pointer_action1 move
_bc pointer_action2 resize_corner
_bc pointer_modifier mod1

# auto-position the horizontal gap
if [ "$(cat $HOME/.local/share/polybar/polybar-position.dat)" = "true" ]; then
  _bc top_padding 0
  _bc bottom_padding 25
  sed -Ei 's/offset =.*/offset = 11x11/g' "$HOME"/.config/dunst/config.ini
else
  _bc top_padding 25
  _bc bottom_padding 0
  sed -Ei 's/offset =.*/offset = 11x36/g' "$HOME"/.config/dunst/config.ini
fi

# window rules
_br 'Dragon-drop:*' state=floating sticky=on
_br '*:zbar' state=floating focus=on
_br 'jetbrains-studio:*:win0' state=floating focus=on
_br 'Localsend_app' state=tiled focus=on
_br 'discord:discord:*' sticky=on
_br 'vesktop:vesktop:*' sticky=on

# mouse settings
_xs "libinput Tapping Enabled" 1
_xs "libinput Tapping Enabled Default" 1
_xs "libinput Disable While Typing Enabled" 0
_xs "libinput Disable While Typing Enabled Default" 0
_xs "libinput Accel Profile Enabled" 1 0
_xs "libinput Accel Profile Enabled Default" 1 0
_xs "libinput Accel Profiles Available" 1 0
_xsw "libinput Accel Speed" -0.3

# keyboard setttings
setxkbmap -option grp:ctrls_toggle tr,es
setxkbmap -option caps:swapescape

# no beep in terminal
xset b 0

# autostart
. /home/skarphet/.config/bspwm/autostart
