#!/bin/sh

input_1="$1"
input_2="$2"

resize_for_phone(){
  mogrify -path ./ -write resized-$input_2 -resize 720x1560^ -gravity Center -extent 720x1560 ./$input_2
}

camswitch() {
  if lsmod | grep -q uvcvideo
  then
    sudo modprobe -r uvcvideo
    echo "Webcam disabled."
  else 
    sudo modprobe uvcvideo
    echo "Webcam enabled."
  fi
}

image_to_clipboard() { 
  xclip -selection clipboard -t image/$(file --extension $input_2 | sed -n 's/^.*:\ //p') -i $input_2
}

weather() {
if [[ "$input_2" = "" ]]; then
  curl -H "Accept-Language: tr" wttr.in
else
  curl -H "Accept-Language: tr" wttr.in/$input_2
fi
}

colors_match() {
    T='ABC'   # The text for the color test
    
    echo -e "\n         def     40m     41m     42m     43m     44m     45m     46m     47m";
    
    for FGs in '    m' '   1m' '  30m' '1;90m' '  31m' '1;91m' '  32m' \
               '1;92m' '  33m' '1;93m' '  34m' '1;94m' '  35m' '1;95m' \
               '  36m' '1;96m' '  37m' '1;97m';
    
      do FG=${FGs// /}
      echo -en " $FGs \033[$FG  $T  "
      
      for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
        do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
      done
      echo;
    done
    echo
}

colors() {
f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
for i in {0..7}; do
    printf -v fbright$i %b "\e[9${i}m"
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'
 
 
printf "
 $f1███$d$fbright$fbright1▄$t  $f2███$d$fbright$fbright2▄$t  $f3███$d$fbright3▄$t  $f4███$d$fbright4▄$t  $f5███$d$fbright5▄$t  $f6███$d$fbright6▄$t  $f7███$d$fbright7▄$t  
 $f1███$d$fbright$fbright1█$t  $f2███$d$fbright$fbright2█$t  $f3███$d$fbright3█$t  $f4███$d$fbright4█$t  $f5███$d$fbright5█$t  $f6███$d$fbright6█$t  $f7███$d$fbright7█$t  
 $f1███$d$fbright$fbright1█$t  $f2███$d$fbright$fbright2█$t  $f3███$d$fbright3█$t  $f4███$d$fbright4█$t  $f5███$d$fbright5█$t  $f6███$d$fbright6█$t  $f7███$d$fbright7█$t  
 $d$fbright1 ▀▀▀   $fbright2▀▀▀   $fbright3▀▀▀   $fbright4▀▀▀   $fbright5▀▀▀   $fbright6▀▀▀   $fbright7▀▀▀
"

}

polybar_toggle(){
if [ ! -f "/tmp/polybar_toggle.dat" ] ; then
  polybar_toggle=1
  echo "${polybar_toggle}" > /tmp/polybar_toggle.dat
else
  polybar_toggle=`cat /tmp/polybar_toggle.dat`
fi

if [[ $polybar_toggle -eq 1 ]]
then
    polybar-msg cmd hide
    bspc config bottom_padding 0
    polybar_toggle=0
else
    polybar-msg cmd show
    bspc config bottom_padding 22
    polybar_toggle=1
fi

echo "${polybar_toggle}" > /tmp/polybar_toggle.dat
	
}

powersave(){
	if killall picom
	then
		printf '%b\n' "\e[1;31m[*] \e[0mKilled picom."
	fi

	if killall polybar
	then
		printf '%b\n' "\e[1;31m[*] \e[0mKilled polybar."
	fi

	if bspc config bottom_padding 0
	then
		printf '%b\n' "\e[1;31m[*] \e[0mChanged the bspwm padding."
	fi

	if xbacklight -set 40
	then
		printf '%b\n' "\e[1;33m[-] \e[0mDecreased the brightness."
	fi	
}

print_usage(){
  printf '\n%b\n' "  \e[1mBUNDLE OF OFTUSED TOOLS\e[0m"

  printf '%b\n' "  bundle {-C --colors2}              show colors in different backgrounds"
  printf '%b\n' "  bundle {-P --powersave}            turn on the power saving mode"
  printf '%b\n' "  bundle {-b --polybar-toggle}       toggle polybar"
  printf '%b\n' "  bundle {-c --colors}               show colors"
  printf '%b\n' "  bundle {-h --help}                 print this message"
  printf '%b\n' "  bundle {-i --image-to-clipboard}   pipe image to clipboard"
  printf '%b\n' "  bundle {-p --wrff}                 resize an image for 1560x720 screens"
  printf '%b\n' "  bundle {-s --cam-switch}           switch the cam (on/off)"
  printf '%b\n' "  bundle {-w --weather}              show the weather for the specified city"
}

case $1 in
  --cam-switch | -s) camswitch ;;
  --colors | -c) colors ;;
  --colors2 | -C) colors_match ;;
  --image-to-clipboard | -i) image_to_clipboard ;;
  --polybar-toggle | -b) polybar_toggle ;;
  --powersave | -P) powersave ;;
  --weather | -w) weather ;;
  --wrff | -p) resize_for_phone ;;
  --yks | -y) yks ;;
  *) print_usage
     exit 1 ;;
esac

