#!/bin/bash

selection=$(echo -e "󰎁  movie mode\n  normal mode\n󰋰  grayscale mode\n󰴅  blue light filter mode\n󰉦  vibrant mode" | rofi -dmenu -p "   modes")

movie_mode() {
  # Hide borders, padding, and gaps (handled via Hyprland config reload)
  hyprctl keyword decoration:rounding 0
  hyprctl keyword general:border_size 0
  hyprctl keyword general:gaps_in 0
  hyprctl keyword general:gaps_out 0

  # Set a black wallpaper
  hyprctl hyprpaper preload "$HOME/img/wal/solid-black.png"
  hyprctl hyprpaper wallpaper "eDP-1,$HOME/img/wal/solid-black.png"
  hyprctl hyprpaper wallpaper "HDMI-A-1,$HOME/img/wal/solid-black.png"

  if [ ! -f "/tmp/waybar_toggle.dat" ]; then
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  else
    waybar_toggle=$(cat /tmp/waybar_toggle.dat)
  fi

  if [[ $waybar_toggle -eq 1 ]]; then
    pkill -SIGUSR1 waybar
    waybar_toggle=0
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  fi
}

normal_mode() {
  # Reload Hyprland config to reset to defaults
  hyprctl reload
  hyprctl hyprpaper wallpaper "HDMI-A-1, ~/img/.wallpaper2"
  hyprctl hyprpaper wallpaper "eDP-1, ~/img/.wallpaper1"

  if [ ! -f "/tmp/waybar_toggle.dat" ]; then
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  else
    waybar_toggle=$(cat /tmp/waybar_toggle.dat)
  fi

  if [[ $waybar_toggle -eq 0 ]]; then
    pkill -SIGUSR1 waybar
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  fi
}

grayscale_mode() {
  # Apply grayscale shader
  hyprctl keyword decoration:blur false
  hyprctl keyword decoration:screen_shader "$HOME/.config/hypr/shaders/grayscale.frag"
}

bluelight_filter() {
  hyprctl keyword decoration:blur false
  hyprctl keyword decoration:screen_shader "$HOME/.config/hypr/shaders/blfilter.frag"
}

vibrant_mode() {
  hyprctl keyword decoration:blur false
  hyprctl keyword decoration:screen_shader "$HOME/.config/hypr/shaders/vibrance.frag"
}

case $selection in
"󰎁  movie mode")
  movie_mode && dunstify -r 2903 -i colormanagement "movie" "enjoy your movie! 🍿"
  ;;
"  normal mode")
  normal_mode && dunstify -r 2903 -i colormanagement "default" "back to default."
  ;;
"󰋰  grayscale mode")
  grayscale_mode && dunstify -r 2903 -i colormanagement "grayscale" "b&w forever."
  ;;
"󰴅  blue light filter mode")
  bluelight_filter && dunstify -r 2903 -i colormanagement "blue light filter" "protect your eyes."
  ;;
"󰉦  vibrant mode")
  vibrant_mode && dunstify -r 2903 -i colormanagement "vibrant" "colorful colors."
  ;;
esac
