#!/bin/bash

selection=$(echo -e "󱐋  zen mode\n󰎁  movie mode\n  normal mode\n󰋰  grayscale mode\n󰴅  blue light filter mode\n󰉦  vibrant mode" | rofi -dmenu -p "    modes")

zen_mode() {
  hyprctl keyword decoration:rounding 0
  hyprctl keyword general:border_size 0
  hyprctl keyword general:gaps_in 0
  hyprctl keyword general:gaps_out 0
}

movie_mode() {
  hyprctl keyword decoration:rounding 0
  hyprctl keyword general:border_size 0
  hyprctl keyword general:gaps_in 0
  hyprctl keyword general:gaps_out 0

  hyprctl hyprpaper preload "$HOME/img/wal/solid-black.png"
  hyprctl hyprpaper wallpaper "eDP-1,$HOME/img/wal/solid-black.png"
  hyprctl hyprpaper wallpaper "HDMI-A-1,$HOME/img/wal/solid-black.png"

  if [ ! -f "/tmp/waybar_toggle.dat" ]; then
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  else
    waybar_toggle=$(cat /tmp/waybar_toggle.dat)
  fi

  if [[ $waybar_toggle -eq 1 ]]; then
    pkill -SIGUSR1 waybar
    waybar_toggle=0
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  fi
}

normal_mode() {
  hyprctl reload
  hyprctl hyprpaper wallpaper "HDMI-A-1, ~/img/.wallpaper_big.png"
  hyprctl hyprpaper wallpaper "eDP-1, ~/img/.wallpaper_small.png"

  if [ ! -f "/tmp/waybar_toggle.dat" ]; then
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  else
    waybar_toggle=$(cat /tmp/waybar_toggle.dat)
  fi

  if [[ $waybar_toggle -eq 0 ]]; then
    pkill -SIGUSR1 waybar
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  fi
}

grayscale_mode() {
  # Apply grayscale shader
  hyprctl keyword decoration:blur false
  hyprctl keyword decoration:screen_shader "$HOME/.config/hypr/shaders/grayscale.frag"
}

bluelight_filter() {
  hyprctl keyword decoration:blur false
  hyprctl keyword decoration:screen_shader "$HOME/.config/hypr/shaders/blfilter.frag"
}

vibrant_mode() {
  hyprctl keyword decoration:blur false
  hyprctl keyword decoration:screen_shader "$HOME/.config/hypr/shaders/vibrance.frag"
}

case $selection in
"󱐋  zen mode")
  zen_mode && dunstify -a "modes" -r 2903 -i crosshairs "zen" "start focusing on your task!"
  ;;
"󰎁  movie mode")
  movie_mode && dunstify -a "modes" -r 2903 -i filmgrain "movie" "enjoy your movie! 🍿"
  ;;
"  normal mode")
  normal_mode && dunstify -a "modes" -r 2903 -i reply "default" "back to default."
  ;;
"󰋰  grayscale mode")
  grayscale_mode && dunstify -a "modes" -r 2903 -i edit-select-invert "grayscale" "b&w forever."
  ;;
"󰴅  blue light filter mode")
  bluelight_filter && dunstify -a "modes" -r 2903 -i redeyes "blue light filter" "protect your eyes."
  ;;
"󰉦  vibrant mode")
  vibrant_mode && dunstify -a "modes" -r 2903 -i color-fill "vibrant" "colorful colors."
  ;;
esac
