#!/bin/bash

[ -d $HOME/.img/ss/null ] || mkdir $HOME/.img/ss/null
dest="$HOME/img/ss/null/$(date +'%Y-%m-%d_%H.%M.%S').png"

selection_screenshot() {
	if maim --hidecursor --select --color=0,0,0,0.6 --highlight $dest
	then
		last_file=$(ls -t $HOME/img/ss/null | head -1)
		dunstify -I "$HOME/img/ss/null/$last_file" --urgency=LOW "peynir" "ekran görüntüsü alındı."
		ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/device-added.oga
		sleep 0.1
		xclip -selection clipboard -t image/png -i $HOME/img/ss/null/$last_file
	fi

}

full_screenshot(){
	if maim --hidecursor $dest
	then
		last_file=$(ls -t $HOME/img/ss/null | head -1)
		dunstify -I "$HOME/img/ss/null/$last_file" --urgency=LOW "peynir" "ekran görüntüsü alındı."
		ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/device-added.oga
		sleep 0.1
		xclip -selection clipboard -t image/png -i $HOME/img/ss/null/$last_file
	fi
}

case $1 in
	select) selection_screenshot ;;
	full) full_screenshot ;;
esac
