#!/bin/bash

first_input="$1"
second_input="$2"

select_screencast() {
	ffmpeg -framerate 60 -f x11grab $(slop -f '-video_size %wx%h -i :0.0+%x,%y') /home/<your username>/vid/sc/$(date +'%Y-%m-%d_%H.%M.%S').mp4
}

fullscreen_screencast() {
	ffmpeg -video_size 1920x1080 -framerate 60 -f x11grab -i :0.0 /home/<your username>/vid/sc/$(date +'%Y-%m-%d_%H.%M.%S').mp4
}

print_usage() {
	echo
	echo -e "\e[1mscreencast"
	echo -e " \e[0;39mscreencast {-f --fullscreen}    record fullscreen"
	echo -e " \e[0;39mscreencast {-s --select}        record the selected window"
	echo
}

case $first_input in
	--select | -s) select_screencast ;;
	--fullscreen | -f) fullscreen_screencast ;;
	*) print_usage ;;
esac
