#!/bin/bash

selection=$(echo -e "📽️ film mode\n💻 normal mode\n🦇 grayscale mode" | rofi -dmenu -p "start")

film_mode() {
  polybar_toggle=0
  echo "${polybar_toggle}" >/tmp/polybar_toggle.dat

  polybar-msg cmd hide
  feh --no-fehbg --bg-fill "$HOME/img/wal/just-black.png"
  bspc config bottom_padding 0
  bspc config top_padding 0
}

grayscale_mode() {
  killall picom > /dev/null
	sleep 0.5
  picom --config "$HOME"/.config/picom/picom.conf --window-shader-fg "$HOME"/.local/share/picom/shaders/grayscale.glsl --log-level ERROR --log-file "$HOME"/.cache/logs/autostart/picom.log &
}

normal_mode() {
	bspc wm -r 
  polybar_toggle=1
  echo "${polybar_toggle}" >/tmp/polybar_toggle.dat
  polybar-msg cmd show &
}

case $selection in
"📽️ film mode")
  film_mode && dunstify -r 2903 -i paint-palette "theme changed to film mode" "enjoy your movie! 🍿"
  ;;
"💻 normal mode")
  normal_mode && dunstify -r 2903 -i paint-palette "theme changed back to normal" "back to default."
  ;;
"🦇 grayscale mode")
  grayscale_mode && dunstify -r 2903 -i paint-palette "theme changed to grayscale" "b&w forever."
  ;;
esac
