#!/bin/bash

selection=$(echo -e "👨🏻‍💻 coding\n📜 translation\n🔠 language learning" | rofi -dmenu -p "select workspace")

coding_workspaces() {
  # Setting rules for opening applications in specific workspaces
  project_rofi="$(echo -e "🦀 learn rust\n🌈 mcfetch\n🎨 dotfiles\n📈 learn data science\n🔒 privacy-redirector\n🏗️ learn dsa" | rofi -dmenu -p 'select the environment')"
  lazygit_ws=4
  terminal_ws=3
  browser_ws=2
  code_ws=1

  launch() {
    bspc desktop -f $code_ws && alacrittynvim --working-directory="$HOME/$project_selection" -e /bin/zsh -c "nvim; zsh" &
    sleep 0.3
    bspc desktop -f $browser_ws && chromium --new-window https://chat.openai.com/ $project_url $extra_url &
    sleep 1.5
    bspc desktop -f $terminal_ws && alacritty --working-directory="$project_selection" -e zsh &
    sleep 0.3
    bspc desktop -f $lazygit_ws && alacritty --working-directory="$project_selection" -e zsh -c "lazygit; zsh" &
    sleep 0.3
    bspc desktop -f $code_ws
  }

  case "$project_rofi" in
  "📈 learn data science")
    project_selection="code/git/learning/learn-data-science"
    project_url="https://github.com/dybdeskarphet/learn-data-science"
    launch
    ;;
  "🏗️ learn dsa")
    project_selection="code/git/learning/learn-dsa"
    project_url="https://github.com/dybdeskarphet/learn-dsa"
    extra_url="https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms/learn/lecture"
    launch
    ;;
  "🎨 dotfiles")
    project_selection="code/git/personal/dotfiles"
    project_url="https://github.com/dybdeskarphet/dotfiles"
    launch
    ;;
  "🔒 privacy-redirector")
    project_selection="code/git/personal/privacy-redirector"
    project_url="https://github.com/dybdeskarphet/privacy-redirector"
    launch
    ;;
  "🌈 mcfetch")
    project_selection="code/git/personal/mcfetch"
    project_url="https://github.com/dybdeskarphet/mcfetch"
    code_ws=1
    terminal_ws=3
    lazygit_ws=3
    browser_ws=2
    launch
    ;;
  "🦀 learn rust")
    project_selection="code/git/learning/learn-rust"
    project_url="https://github.com/dybdeskarphet/learn-rust"
    extra_url="https://doc.rust-lang.org/stable/book/"
    terminal_ws=2
    browser_ws=1
    lazygit_ws=2
    launch
    ;;
  *)
    exit 1
    ;;
  esac
}

translation_workspace() {
  bspc desktop -f 1 && alacrittynvim --working-directory="$HOME" -e /bin/zsh -c "nvim $HOME/doc/wiki $HOME/doc/notes/todo/translation/archwiki.md; zsh" &
  sleep 0.3
  bspc desktop -f 3 && zathura "$HOME/doc/book/cs/Bilişim Terimleri Sözlüğü (TSE).pdf" &
  sleep 1.0
  bspc desktop -f 2 && alacritty -e zsh -c "fftor https://wiki.archlinux.org/title/User:Dybdeskarphet https://www.deepl.com/translator https://tureng.com/en/turkish-english" &
}

case $selection in
"👨🏻‍💻 coding")
  coding_workspaces
  ;;
"📜 translation")
  translation_workspace
  ;;
"🔠 language learning")
  language_learning_workspace
  ;;
esac
