#!/bin/bash
capacity=$(cat /sys/class/power_supply/BAT0/capacity)
bat_status="$(cat /sys/class/power_supply/BAT0/status)"

if [[ $bat_status = "Charging" || $bat_status = "Full" ]]; then
	if [[ $capacity -gt 90 ]]; then
		dunstify -t 10000 -r 87873 -i battery-full "pil %90'in üstünde" "cihazınızı şarjdan çıkarabilirsiniz."
	fi
	exit 1
fi

if [[ $capacity -lt 15 && $capacity -gt 10 ]]; then
	dunstify -t 10000 -r 87873 -i battery-empty "pil %15'in altında" "cihazınızı şarja takmanız tavsiye edilir."
elif [[ $capacity -lt 10 && $capacity -gt 5 ]]; then
	dunstify -t 10000 -r 87873 -u critical -i battery-empty "pil düşük!" "cihaz birkaç dakika içinde kapanabilir."
elif [[ $capacity -lt 5 ]]; then
	dunstify -t 10000 -r 87873 -u critical -i battery-empty "pil neredeyse boş!" "cihazınız birazdan kapanacak!"
	ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/dialog-warning.oga
	xbacklight -set 20
fi
