#!/bin/bash

dunstify_vol() {
	dunstify -h int:value:$(pamixer --get-volume) -i $1 -r 92030 -t 3000 "ses $(pamixer --get-volume-human)" 
}

case $1 in
	up) pamixer --allow-boost -i 5 && dunstify_vol audio-volume-high ;;
	down) pamixer --allow-boost -d 5 && dunstify_vol audio-volume-low ;;
	full) pamixer --set-volume 100 && dunstify_vol audio-volume-high ;;
	off) pamixer --set-volume 0 && dunstify_vol audio-volume-low ;;
	toggle)
		case $(pamixer --get-volume-human) in
			muted) pamixer -t && dunstify_vol audio-volume-high ;;
			*) pamixer -t && dunstify -h int:value:$(pamixer --get-volume) -i audio-volume-muted -r 92030 -t 3000 "susturuldu" ;;
	  	esac
	;;
esac
