#!/bin/bash

mic_toggle() {
  CARD_INDEX=1
  CONTROL_NAME='Capture'

  amixer -c $CARD_INDEX sset $CONTROL_NAME toggle
  pkill -RTMIN+5 waybar

  # Get the updated status after toggling
  mic_status=$(amixer -c $CARD_INDEX sget $CONTROL_NAME | grep -o "\[[a-z]*\]")
}

case $1 in
volume)
  case $2 in
  up)
    pamixer -i 5 &
    paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga &
    ;;
  down)
    pamixer -d 5 &
    paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga &
    ;;
  full) pamixer --set-volume 100 ;;
  off) pamixer --set-volume 0 ;;
  toggle)
    case $(pamixer --get-volume-human) in
    muted) pamixer -t ;;
    *) pamixer -t ;;
    esac
    ;;
  esac
  ;;
backlight)
  case $2 in
  down) xbacklight -dec 10 && dunstify_bl ;;
  up) xbacklight -inc 10 && dunstify_bl ;;
  full) xbacklight -set 100 -steps 10 && dunstify_bl ;;
  off) xbacklight -set 1 -steps 10 && dunstify_bl ;;
  esac
  ;;

togglemic)
  mic_toggle
  ;;
esac
