#!/bin/bash

script_name="$(basename "$0")"

colors_match() {
  T='ABC' # The text for the color test

  echo -e "\n         def     40m     41m     42m     43m     44m     45m     46m     47m"

  for FGs in '    m' '   1m' '  30m' '1;90m' '  31m' '1;91m' '  32m' \
    '1;92m' '  33m' '1;93m' '  34m' '1;94m' '  35m' '1;95m' \
    '  36m' '1;96m' '  37m' '1;97m'; do
    FG=${FGs// /}
    echo -en " $FGs \033[$FG  $T  "

    for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
      echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m"
    done
    echo
  done
  echo
}

colors() {
  f=3
  b=4
  for j in f b; do
    for i in {0..7}; do
      printf -v $j"$i" %b "\e[${!j}${i}m"
    done
  done

  for i in {0..7}; do
    printf -v fbright"$i" %b "\e[9${i}m"
  done

  d=$'\e[1m'
  t=$'\e[0m'
  v=$'\e[7m'

  printf "
$f1███$d$fbright$fbright1▄$t  $f2███$d$fbright$fbright2▄$t  $f3███$d$fbright3▄$t  $f4███$d$fbright4▄$t  $f5███$d$fbright5▄$t  $f6███$d$fbright6▄$t  $f7███$d$fbright7▄$t  
$f1███$d$fbright$fbright1█$t  $f2███$d$fbright$fbright2█$t  $f3███$d$fbright3█$t  $f4███$d$fbright4█$t  $f5███$d$fbright5█$t  $f6███$d$fbright6█$t  $f7███$d$fbright7█$t  
$f1███$d$fbright$fbright1█$t  $f2███$d$fbright$fbright2█$t  $f3███$d$fbright3█$t  $f4███$d$fbright4█$t  $f5███$d$fbright5█$t  $f6███$d$fbright6█$t  $f7███$d$fbright7█$t  
$d$fbright1 ▀▀▀   $fbright2▀▀▀   $fbright3▀▀▀   $fbright4▀▀▀   $fbright5▀▀▀   $fbright6▀▀▀   $fbright7▀▀▀
"
}

print_usage() {
  printf '\n%b\n' "  \e[1mCOLORS\e[0m"

  printf '%b\n' "  $script_name {-C --colors2}  show colors in different backgrounds"
  printf '%b\n\n' "  $script_name {-c --colors}   show colors"
}

case $1 in
--colors | -c) colors ;;
--colors2 | -C) colors_match ;;
*) print_usage ;;
esac
