#!/usr/bin/env python3
from pathlib import Path
import sys
import openrazer.client


def main():
    devices = openrazer.client.DeviceManager().devices

    path = Path.home() / ".config" / "openrazer" / "matugen.txt"

    try:
        with open(path, "r") as f:
            rgb_line = f.readline().strip()
    except FileNotFoundError:
        print(
            f"Error: The source file does not exist :/\nYou have to have a file that contains 'rgb(r,g,b)' values at {path}.\nPreferably, use matugen."
        )
        exit(1)
    except PermissionError:
        print(f"Error: You don't have permission to read {path} :|")
        exit(1)
    except Exception as e:
        print(f"An unexpected error occurred: {e} :O")
        exit(1)

    r, g, b = [int(x.strip()) for x in rgb_line[4:-1].split(", ")]

    if not devices:
        print("No Razer device is found.")
        exit(1)

    for dev in devices:
        if dev is None:
            print(f"Unknown device.")
            exit(1)

    if len(sys.argv) < 2:
        print("Usage: maturazer [reactive|ripple|static] <fastest,fast,normal,slow>")
        return

    mode = sys.argv[1]

    if mode == "reactive":
        for device in devices:
            if len(sys.argv) < 3:
                print("You have to specify time too")
                exit(1)

            time = sys.argv[2]

            if time == "fastest":
                time_openrazer = 0x01
            elif time == "fast":
                time_openrazer = 0x02
            elif time == "normal":
                time_openrazer = 0x03
            elif time == "slow":
                time_openrazer = 0x04
            else:
                time_openrazer = 0x01

            print(f"Found {device.name}")
            device.fx.reactive(r, g, b, time_openrazer)
            print("Reactive mode selected.")
    elif mode == "ripple":
        for device in devices:
            print(f"Found {device.name}")
            device.fx.ripple(r, g, b)
            print("Ripple mode selected.")
    elif mode == "static":
        for device in devices:
            print(f"Found {device.name}")
            device.fx.static(r, g, b)
            print("Static mode selected.")
    else:
        print("Unknown mode:", mode)


if __name__ == "__main__":
    main()
