#!/bin/bash

script_name="$(basename "$0")"

print_usage() {
  printf '\n%b\n' "  \e[1mMEDIA CONTROL\e[0m"
  printf '%b\n' "  $script_name volume <up|down|full|off|toggle>    control the volume"
  printf '%b\n\n' "  $script_name backlight <down|up|full|off>        control the backlight"
}

mic_toggle() {
  CARD_INDEX=1
  CONTROL_NAME='Capture'

  amixer -c $CARD_INDEX sset $CONTROL_NAME toggle
  pkill -RTMIN+5 waybar

  # Get the updated status after toggling
  mic_status=$(amixer -c $CARD_INDEX sget $CONTROL_NAME | grep -o "\[[a-z]*\]")
}

case $1 in
volume)
  case $2 in
  up)
    pamixer -i 5 &
    paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga &
    ;;
  down)
    pamixer -d 5 &
    paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga &
    ;;
  full) pamixer --set-volume 100 ;;
  off) pamixer --set-volume 0 ;;
  toggle)
    case $(pamixer --get-volume-human) in
    muted) pamixer -t ;;
    *) pamixer -t ;;
    esac
    ;;
  esac
  ;;
backlight)
  case $2 in
  down) brightnessctl set 10%- ;;
  up) brightnessctl set +10% ;;
  full) brightnessctl set 100% ;;
  off) brightnessctl set 1% 10 ;;
  esac
  ;;

togglemic)
  mic_toggle
  ;;
*) print_usage ;;
esac
