#!/bin/bash

selection=$(echo -e "󰎁  movie mode\n  normal mode" | rofi -dmenu -theme ~/.local/share/rofi/themes/basic_launcher/rounded_with_listview.rasi -p "    modes")

movie_mode() {
  niri-genconfig generate movie

  if [ ! -f "/tmp/waybar_toggle.dat" ]; then
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  else
    waybar_toggle=$(cat /tmp/waybar_toggle.dat)
  fi

  if [[ $waybar_toggle -eq 1 ]]; then
    pkill -SIGUSR1 waybar
    waybar_toggle=0
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  fi
}

normal_mode() {
  niri-genconfig generate

  if [ ! -f "/tmp/waybar_toggle.dat" ]; then
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  else
    waybar_toggle=$(cat /tmp/waybar_toggle.dat)
  fi

  if [[ $waybar_toggle -eq 0 ]]; then
    pkill -SIGUSR1 waybar
    waybar_toggle=1
    echo "${waybar_toggle}" >/tmp/waybar_toggle.dat
  fi
}

case $selection in
"󰎁  movie mode")
  movie_mode && dunstify -a "modes" -r 2903 -i filmgrain "movie" "enjoy your movie! 🍿"
  ;;
"  normal mode")
  normal_mode && dunstify -a "modes" -r 2903 -i reply "default" "back to default."
  ;;
esac
