#!/bin/bash

script_name="$(basename "$0")"

read_qr() {
  printf '%b\n' "\e[32mShow the code to the camera.\e[0m"
  zbarcam || printf '\n%b\n\n' "\e[31merror: \e[0mplease install the zbar package."
}

create_qr() {
  if qrencode --foreground=000000 --background=ffffff -l M -s 20 -o /tmp/lastqr.png "$1"; then
    nsxiv /tmp/lastqr.png >/dev/null 2>&1
  elif [[ $(command -v qrencode) = "" ]]; then
    printf '\n%b\n\n' "\e[31merror: \e[0mplease install the qrencode package."
  else
    nsxiv /tmp/lastqr.png >/dev/null 2>&1
  fi
}

print_usage() {
  printf '\n%b\n' "  \e[1mQR\e[0m"
  printf '%b\n' "  $script_name {-r --read}    reads qr code from webcam"
  printf '%b\n' "  $script_name [text]         creates qr code from text"
  printf '%b\n\n' "  $script_name                opens the last generated qr code"
}

case $1 in
-r | --read) read_qr ;;
-h | --help)
  print_usage
  exit 1
  ;;
*) create_qr $1 ;;
esac
